### ISSUE TITLE
Project informations

### ISSUE THREAD

**Issue by BenRoe** [holtenc/prime_ble#1]
Hello,
i found your project and it looks interesting.
Is it WIP? Can you add some information to make it easier for other to build this project?

**Comment by holtenc** [comment]
Hi, im sorry I must not have notifications turned on. If you've got specific questions I'm happy to help. Assuming you haven't lost interest over the past 3 months :D

I guess you could call it a work in progress, though I don't have much intention of continuing to work on it.
